// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCnD8rrSxsscMzeO2r2E8-H117OypVyMU',
    appId: '1:655153439118:web:2b0b34dada857ffba284df',
    messagingSenderId: '655153439118',
    projectId: 'eduverse-36b0d',
    authDomain: 'eduverse-36b0d.firebaseapp.com',
    storageBucket: 'eduverse-36b0d.firebasestorage.app',
    measurementId: 'G-7B78Z353Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsRerM4WsfdlKWzLlSb15ZYS_lY5jq8VA',
    appId: '1:655153439118:android:4664f5b4da8d7b83a284df',
    messagingSenderId: '655153439118',
    projectId: 'eduverse-36b0d',
    storageBucket: 'eduverse-36b0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtBv_wxMM6d1R1m4igIRC03unOAzNyY40',
    appId: '1:655153439118:ios:56c1df7553d6a5c2a284df',
    messagingSenderId: '655153439118',
    projectId: 'eduverse-36b0d',
    storageBucket: 'eduverse-36b0d.firebasestorage.app',
    iosBundleId: 'net.eduverseapp.platform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtBv_wxMM6d1R1m4igIRC03unOAzNyY40',
    appId: '1:655153439118:ios:56c1df7553d6a5c2a284df',
    messagingSenderId: '655153439118',
    projectId: 'eduverse-36b0d',
    storageBucket: 'eduverse-36b0d.firebasestorage.app',
    iosBundleId: 'net.eduverseapp.platform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCnD8rrSxsscMzeO2r2E8-H117OypVyMU',
    appId: '1:655153439118:web:94bb9f88fe761334a284df',
    messagingSenderId: '655153439118',
    projectId: 'eduverse-36b0d',
    authDomain: 'eduverse-36b0d.firebaseapp.com',
    storageBucket: 'eduverse-36b0d.firebasestorage.app',
    measurementId: 'G-XBV4ELCV97',
  );
}
